### PR TITLE
Loop on properties instead of in everything

### PR DESCRIPTION
**Pull request by Shahor**
Some people extend the native prototypes and that breaks the batch sending of stats.

### CODE REVIEW

**Comment by Shahor** [comment]
I don't understand why the "checks" have failed. The tests are good on my machine.

**Comment by arnaudmm** [comment]
+1 for this PR, it's simple to review, come on!

**Comment by gcochard** [comment]
@Shahor the tests failed because npm `v1.2.x` which is installed by default on node < `v10.x` doesn't know how to handle the `^` semver marker. If you update the .travis.yml to run `npm install -g npm` in `before_install` like [underscore does](https://github.com/jashkenas/underscore/commit/4de07c008e53f2d4d8411fc315662496e80a8ea1).

**Comment by Shahor** [comment]
There we go then :]

**Comment by Shahor** [comment]
> Hello [hello, hello...]
> Is there anybody in there?
> Just nod if you can hear me
> Is there anyone home?

Pink floyd

(But really, what's happening to this pr ?)

**Comment by Shahor** [comment]
Up

**Comment by Shahor** [comment]
What's happening to this?

**Comment by Shahor** [comment]
Nothing's gonna be happening here apparently

**Pull request closed without merging**
