### PR TITLE
Avoid corrupt UDP packages due to being to large

### PR DESCRIPTION
**Pull request by Tenzer**
We experience an issue with incomplete data being sent through lynx, because of bulks of several hundreds of metrics at a time are being sent with the `send()` function. The incomplete data is because of the UDP package size being to large for all systems to handle, and thus being truncated on the way from lynx to StatsD.
This patch will put every 5 metrics in its own UDP package which should work for basically all metrics.

I have tried to write the code in the same format as the existing code, but let me know if there are any changes you would like me to make.

### CODE REVIEW

**Comment by dscape** [comment]
Sorry totally missed this.

Still important for me to merge this?

I can give you npm/github access if you like.

**Comment by dscape** [comment]
Thanks for reporting this. After a close look I couldn't understand the why behind the `n=5`. Can you clarify?

**Comment by dscape** [comment]
From some research. Seems like it's safe to have a UDP packet that is 512 bytes. Occasionally the default is 8192 bytes, and in Windows the max is 65507 bytes.

**Comment by dscape** [comment]
Related issue: https://github.com/goncalopereira/statsd-csharp-client/pull/26

**Comment by dscape** [comment]
Also related, from node core[1](http://nodejs.org/api/dgram.html)

# A Note about UDP datagram size

The maximum size of an IPv4/v6 datagram depends on the MTU (Maximum Transmission Unit) and on the Payload Length field size.
- The Payload Length field is 16 bits wide, which means that a normal payload cannot be larger than 64K octets including internet header and data (65,507 bytes = 65,535 − 8 bytes UDP header − 20 bytes IP header); this is generally true for loopback interfaces, but such long datagrams are impractical for most hosts and networks.
- The MTU is the largest size a given link layer technology can support for datagrams. For any link, IPv4 mandates a minimum MTU of 68 octets, while the recommended MTU for IPv4 is 576 (typically recommended as the MTU for dial-up type applications), whether they arrive whole or in fragments. For IPv6, the minimum MTU is 1280 octets, however, the mandatory minimum fragment reassembly buffer size is 1500 octets. The value of 68 octets is very small, since most current link layer technologies have a minimum MTU of 1500 (like Ethernet).

Note that it's impossible to know in advance the MTU of each link through which a packet might travel, and that generally sending a datagram greater than the (receiver) MTU won't work (the packet gets silently dropped, without informing the source that the data did not reach its intended recipient).

**Comment by dscape** [comment]
I think I got my affairs in order. This is what needs to happen for this to get merged:

### 1. Make the MTU configurable, ensuring it's always above 68 since lower is just a waste of bandwidth.

```
var connection = new lynx('localhost', 1234, { on_error: on_error, MTU: 576 });
```
1. By default the MTU should be `1500` as that is the default right now. 
2. We should subtract other stuff added being pessimistic; e.g. assuming ipv6
3. Tests should be added that assure changing MTU actually does something, preventing regressions

### 2. Change the code so MTU is respected

I would prefer if we could keep the code nice and functional like that map, but if a for loop is required I'm ok with that too. It just makes it harder to read and with time harder to maintain, also more prone to errors.

But up to you.

### Thank you

Thanks for reporting this. I actually did not think anyone was using this, I'm glad you found it helpful.
Hope you understand that ensuring all these steps will make the library bullet proof and that's good for everyone using it!

Please do send a new PR

**Comment by Tenzer** [comment]
Honestly, the limit of 5 metrics per package was simply a quick way for us to get around this limitation. Counting up the bytes used per metric is a better way to go, but was more when I initially made the pull request. I'll try to see if I get the time to make a new pull request as you request, but I cant promise anything.

**Comment by dscape** [comment]
Thanks @Tenzer — I appreciate the pragmatism but am afraid of the consequences because is possible that a 5 metrics are over ~140 chars. When we state that we fixed something we should try to avoid that being possible :)

Thank you, looking forward to landing your fix.

**Comment by edasque** [comment]
I am seeing the same issue when sending metrics using bucky which uses lynx. Bucky can be very verbose when the page does a lot of Ajax requests (for example) which causes the UDP package to be very large. Any chance of a fix/workaround for this?

**Pull request closed without merging**
