### PR TITLE
Fixes cancelTimeout error (by using clearTimeout).

### PR DESCRIPTION
**Pull request by matthewbennink**
I receive this error message -- `ReferenceError: cancelTimeout is not defined`.  I see that `clearTimeout` is used elsewhere.

Sorry about the whitespace change at the end of the file.  I used Github's web editor and it made the change automatically.

### CODE REVIEW

**Comment by dscape** [comment]
@matthewbennink @rosskukulinski thank you so much for your contribution. very sorry to have missed this for so long! it's now merged and will soon be published

**Comment by stevenbeeckman** [comment]
Still not published?

**Comment by rosskukulinski** [comment]
@stevenbeeckman I pinged @dscape and he just published it.  Should see it sync up on npmjs.org soon.

**Comment by stevenbeeckman** [comment]
Thanks!
Op 14-feb.-2014 01:01 schreef "Ross Kukulinski" notifications@github.com:

**Comment by dscape** [comment]
i can npmown @rosskukulinski if you want?

**Comment by rosskukulinski** [comment]
If you're so inclined @dscape. I keep an eye on things since I wrote and am using [lynx-express](https://github.com/rosskukulinski/lynx-express/) in production.

**Comment by dscape** [comment]
``` sh
$ npm owner ls
npm http GET http://registry.nodejitsu.com/lynx
npm http 200 http://registry.nodejitsu.com/lynx
dscape <nunojobpinto@gmail.com>
lloyd <lloyd@hilaiel.com>
rosskukulinski <rossk@labs.asti-usa.com>
```

**Comment by rosskukulinski** [comment]
with-great-beard-comes-great-responsibility american-apparel-unisex-athletic-tee athletic-grey w760h760

**Pull request merged**
