### PR TITLE
Prevent variables from entering global scope

### PR DESCRIPTION
**Pull request by bog**
Two variables are declared without 'var'.

### CODE REVIEW

**Comment by dscape** [comment]
Thank you, great catch :)

How did you detect this? I want to make sure I update my tools so this doesnt happen again.

Btw they are not entering global scope, I just tested it and there was no such leak

**Comment by dscape** [comment]
These are the leaks currently in the program:

```
leak detected: N
leak detected: M
leak detected: MATRIX_A
leak detected: UPPER_MASK
leak detected: LOWER_MASK
```

All of them because of the random number generator.

**Comment by dscape** [comment]
Never-mind, of course it does create a global leak.

`node-tap` doesn't do global leak check. I'll try to migrate the tests to `specify` later on.

**Comment by bog** [comment]
Mocha complained about global leaks after requiring lynx.

```
  Error: global leaks detected: batch, value
        at Runner.checkGlobals (…/node_modules/mocha/lib/runner.js:135:21)
        at Runner.<anonymous> (…/node_modules/mocha/lib/runner.js:45:44)
```

Thanks for maintaining this library

**Comment by dscape** [comment]
Just updated the library on npm.

`mocha` should have complained a bit more then :)

thanks for the contributions

**Comment by dscape** [comment]
Also did this fix it for you?

**Comment by bog** [comment]
Yes, it does. Thanks.

**Pull request merged**
